spring.application.name=workForceApplication

server.port=5233
spring.datasource.url=jdbc:mysql://localhost:3306/workforce
spring.datasource.username=root
spring.datasource.password=focr2559@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# JPA Batch Size Optimization for faster bulk inserts
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true

fastapi.base-url=http://localhost:8000

prediction.csv.path=C:/Users/muham/IdeaProjects/workforce-model/workforce-forecasting-python/results/predictions.csv

python.api.url=http://localhost:8000/train
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

python.download.url=http://localhost:8000/train/cleaned-dataset
