export const ROUTES = {
  HOMESETTINGS: '/homeSettings',
  DASHBOARD: '/dashboard',
  FORECASTING: '/forecasting',
  AI_MODELS: '/ai-models',
  SHIFTOPTIMIZATION: '/shiftOptimization',
  EMPLOYEES: '/employees',
  ANALYTICS: '/analytics',
  CAPACITYPLANNING: '/capacity-planning',
  MONITOR: '/monitoring',
  BENCHMARK: '/benchmarks',
  REPORT: '/reports',
  NOTIFICATION: '/notifications',
  SETTINGS: '/settings',
}
